//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringTourSystem.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager
    {
        public int manager_id { get; set; }
        public string manager_name { get; set; }
        public string password { get; set; }
        public string access_token { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string display_photo { get; set; }
        public string position { get; set; }
    }
}
