//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringTourSystem.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class place
    {
        public int place_id { get; set; }
        public string province_id { get; set; }
        public int country_id { get; set; }
        public string place_name { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public string cover_photo { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
    }
}
