//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringTourSystem.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tourguide_help
    {
        public int help_id { get; set; }
        public string help_content { get; set; }
        public int sender_id { get; set; }
        public int receiver_id { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string status { get; set; }
    }
}
