//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringTourSystem.Infrastructures.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_schedule
    {
        public int tour_schedule1 { get; set; }
        public int tour_id { get; set; }
        public string place_id { get; set; }
        public string place_name { get; set; }
        public string vehicle { get; set; }
        public System.DateTime time { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string nameProvince { get; set; }
    }
}
